%YAML:1.0

output : "result.png"   
squareX: 9
squareY: 6
#Square side length (in pixels) 
squareLength: 100
#Marker side length (in pixels)
markerLength: 80
margin: 50
#dictionary: DICT_4X4_50=0, DICT_4X4_100=1, DICT_4X4_250=2,"
#  "DICT_4X4_1000=3, DICT_5X5_50=4, DICT_5X5_100=5, DICT_5X5_250=6, DICT_5X5_1000=7, "
#  "DICT_6X6_50=8, DICT_6X6_100=9, DICT_6X6_250=10, DICT_6X6_1000=11, DICT_7X7_50=12,"
#  "DICT_7X7_100=13, DICT_7X7_250=14, DICT_7X7_1000=15, DICT_ARUCO_ORIGINAL = 16}"
dictionaryID: 10
#Number of bits in marker borders 
borderBits:1
showImage : 1

bCreate: 0

bDetect: 1


#Calibration
perFrame: 25

CALIB_FIX_ASPECT_RATIO : 0
CALIB_ZERO_TANGENT_DIST: 1
CALIB_FIX_PRINCIPAL_POINT: 0

#Detector parameters path
dpPath : detector_params.yaml

refinedStrategy: 1
#0 use video file, others use internal cam
camID: 0
inputVideo: "calib1080L.MP4"
saveCamParamPath: "camera1920960L.yaml"
showCorners: 1